name: Build and Upload VSIX

on:
  pull_request:
    branches:
      - "**"

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Build packages (Unix)
        run: ./scripts/build-packages.sh

      - name: Install dependencies (Unix)
        run: ./scripts/install-dependencies.sh

      - name: Run Pre-package
        run: |
          cd extensions/vscode
          npm run prepackage

      - name: Package the extension
        run: |
          cd extensions/vscode
          npx vsce package --no-dependencies

      - name: Add VSIX as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vsix-package
          path: extensions/vscode/*.vsix

  UploadToS3:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download VSIX artifact
        uses: actions/download-artifact@v4
        with:
          name: vsix-package
          path: ./vsix

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: |
          VSIX_FILE=$(find ./vsix -name "*.vsix" | head -n 1)
          echo "Uploading $VSIX_FILE to ${S3_BUCKET_NAME}"
          aws s3 cp "$VSIX_FILE" "s3://${S3_BUCKET_NAME}/"
        env:
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}

